[package]
authors = ["Hunter Jozwiak <hunter.t.joz@gmail.com>"]
description = "Low level bindings to the espeak-ng speech synthesizer."
edition = "2021"
license = "MIT"
name = "espeak-ng-sys"
version = "0.1.0"

[build-dependencies]
bindgen = "0.59.2"
